server:
  port: 8080
  servlet:
    context-path: /orz
  tomcat:
    uri-encoding: utf-8
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/orz?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&useSSL=false
    username: root
    password: 123654cjcj
    driver-class-name: com.mysql.cj.jdbc.Driver
  web:
    resources:
      static-locations: classpath\:/META-INF/resources/,classpath\:/resources/,classpath\:/static/,classpath\:/public/,file\:${web.upload-path}
        classpath:/static/,classpath:/public/,file:${web.upload-path}

#web.upload-path: /root/img/
#
appid: wx93b252758e00e363
secret: fddc8036f7933a0c2fee0c76a9891003
#
#modelId: UHRmUY_tfJ8WhUT0DWthrUie-j1yjTAZx63jXV3WIfA
mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml

#showSql
#logging:
#  level:
#    com:
#      dompine:
#        mapper: debug